# Generated by Django 3.2 on 2023-04-17 10:19

import django.contrib.auth.validators
import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.validators.validate_username, django.contrib.auth.validators.UnicodeUsernameValidator]),
        ),
    ]
