# Generated by Django 3.2 on 2023-04-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='default name', max_length=250),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default slug', unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='default name', max_length=250),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='default slug', unique=True),
        ),
    ]
